spring:
  application:
    name: MyProducer

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 5s
        register: true
        health-check-timeout: 5s

server:
  port: 8081
